### ISSUE TITLE
unfortunately，it do not work in my android studio

### ISSUE THREAD

**Issue by ISX** [u3shadow/RemoveButterKnife#6]
cannot create class "com.u3.MainAction" [Plugin: com.u3coding.removebutterknife]
com.intellij.diagnostic.PluginException: cannot create class "com.u3.MainAction" [Plugin: com.u3coding.removebutterknife]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:177)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:515)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:495)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:488)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:354)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:312)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:125)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:86)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.fillMenu(ActionMenu.java:314)
	at com.intellij.openapi.actionSystem.impl.ActionMenu.access$600(ActionMenu.java:50)
	at com.intellij.openapi.actionSystem.impl.ActionMenu$MenuListenerImpl.menuSelected(ActionMenu.java:268)
	at javax.swing.JMenu.fireMenuSelected(JMenu.java:1028)
	at javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1107)
	at javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:333)
	at javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:215)
	at javax.swing.JMenu.setSelected(JMenu.java:294)
	at com.apple.laf.ScreenMenu$1.run(ScreenMenu.java:117)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at apple.awt.CToolkit$CPeerEvent.dispatch(CToolkit.java:1221)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.diagnostic.PluginException: com/u3/MainAction : Unsupported major.minor version 52.0 [Plugin: com.u3coding.removebutterknife]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:153)
	... 35 more
Caused by: java.lang.UnsupportedClassVersionError: com/u3/MainAction : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
	... 41 more

**Comment by u3shadow** [comment]
Are you use JDK7? may be use jdk 8 could fix this problem
